# General Settings
env: pong-v1
name: pong_es

# Algorithm settings
algorithm: es
population_size: 200
mutation_power: 0.05
learning_rate: 0.1
vbs_steps: 500

# System settings
num_gpus: 0
num_workers: 95
num_cpus_for_driver: 1

# Logging settings
log_level: ERROR
logger_config:
  wandb:
    project: neurocoevolution
num_train_videos: 5

# Experiment Settings
render: false
max_evaluation_steps: 500
evaluation_games: 50
max_timesteps_per_episode: 500
input_channels: 6
number_actions: 4
random_action: 1
random_action_probability: 0.05
stop_criteria:
  timesteps_total: 50_000_000



